const ApiConstants = {
  //   API_MATI: {
  //     BASE_URL: 'https://api.getmati.com/v2',
  //     CREATE_IDENTITY: '/identities',
  //     FLOW_ID: '609c43bfa06db3001b207a8e',
  //     SEND_INPUT: '/send-input',
  //   },
  //   BALANCES: '/balances',
  //   GET_MATIJWT: '/mati/access-token',
  //   GET_VERIFICATION_DATA: '/users/verification-data',
  //   API_TO_TEST_FILE_SUBMISSION: 'http://httpbin.org',
  //   VERIFY_EMAIL: '/users/verify-email',
  //   VERIFY_PHONE: '/users/verify-phone',
  //   SEND_VERIFICATION_CODE: '/users/send-verification-code',
  //   VALIDATE_CODE: '/users/validate-code',
  //   CRUD_COMPANY: '/companies',
  //   GET_COMPANIES_WHERE: '/companies?where',
  //   GET_BRANCHES_WHERE: '/branches?where',
  //   GET_COLLECTION_BOXES: '/collection-boxes',
  //   GET_COLLECTION_BOXES_WHERE: '/collection-boxes?where',
  //   RECHARGE: '/recharges',
  //   SERVICE_PAYMENT: '/bill-payments',
  //   SERVICE_PAYMENT_BARDCODE_SCAN: '/bill-payments/barcode',
  //   SERVICE_PAYMENT_SEARCH_OPTION: '/bill-payments/search-options',
  //   USERS: '/users',
  //   ME: '/me',
  //   ACCOUNTS: '/accounts',
  //   VALIDATE_ACCOUNT: '/accounts/validate',
  //   TRANSFERS: '/transfers',
  //   TRANSFER_CONCEPTS: '/transfers/concepts',
  //   TRANSACTIONS: '/transactions',
  //   LAST_TRANSACTIONS: '/transactions?where[accountId]=',
  //   RECHARGES_WHERE: '/recharges?where',
  //   PENDING_BILLS: '/pendings',
  //   ICONS: {
  //     SERVICES_PAYMENT: '/static/pago-servicio.png',
  //     YOPIT_CARD: '/static/yopit-card.png',
  //   },
  //   TERMS_AND_CONDITIONS_URL: {
  //     es: 'https://s3.sa-east-1.amazonaws.com/yopit.test.public/tc/es-AR/index.html',
  //     zh: ' https://s3.sa-east-1.amazonaws.com/yopit.test.public/tc/zh-CN/index.html',
  //   },
  //   PRIVACY_POLICIES_URL: {
  //     es: 'https://s3.sa-east-1.amazonaws.com/yopit.test.public/pp/es-AR/index.html',
  //     zh: 'https://s3.sa-east-1.amazonaws.com/yopit.test.public/pp/zh-CN/index.html',
  //   },
};

export default ApiConstants;
