export const GET_SELECTED_CITY_WEATHER = 'GET_SELECTED_CITY_WEATHER';
export const RESPONSE_SELECTED_CITY_WEATHER = 'RESPONSE_SELECTED_CITY_WEATHER';
export const ERROR_SELECTED_CITY_WEATHER = 'ERROR_SELECTED_CITY_WEATHER';

export const CLEAR_STATE = 'CLEAR_STATE';
